apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lepjk1hyi-go 
  janus-idp.io/tekton: lepjk1hyi-go
  backstage.io/kubernetes-id: lepjk1hyi-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lepjk1hyi-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml