apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lepjk1hyi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lepjk1hyi-go 
  name: lepjk1hyi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lepjk1hyi-go 
